### ISSUE TITLE
Cannot flash ath79 builds on NS-5ACL

### ISSUE THREAD

**Issue by ESP32the2nd** [TobleMiner/nanostation-ac-openwrt-bin#1]
The ar71 builds are working.

I get following error message with trying ath79 build:

> WA.v8.5.0# /tmp/fwupdate.real -m /tmp/openwrt-ath79-generic-ubnt_nanostation-ac-loco-squashfs-factory.bin
> Invalid version 'WA.ar934x.v6.0.0-OpenWrt-r7995+4-eec677f57d'

**Comment by TobleMiner** [comment]
Thanks for reporting. The version 6.0.0 is indeed wrong. Seems I broke it while generalizing the ubnt image-split build. I'll look into it.

**Comment by TobleMiner** [comment]
Got it. Please feel free to reopen if the issue persists.

If would be real nice if you could report your success at https://github.com/openwrt/openwrt/pull/1346 . It might help getting it merged sooner.

**Comment by ESP32the2nd** [comment]
Was not easy to upgrade. Impossible in web interface. sysupgrade required -F option.

After upgrade, could not change gateway and ip address for eth0 in web interface and uci. Web interface crashed and uci change was ignored. Needed to change it in etc/config. Should I open new ticket about this?

**Comment by TobleMiner** [comment]
I'd suggest flashing the ath79 image using `sysupgrade -v -F -n <image>`. What you are experiencing is most likely just inherent incompatibility between ar71xx and ath79 configs. Switching from ar71xx to ath79 requires re-initialization of most config files. The device refusing to upgrade to the ath79 image is a result of the target change, too. Changing targets is not really supported in OpenWrt. Once you flash the ath79 image with above command it should work just fine.

**Comment by baalwy** [comment]
How to add all Channels for M5 and M2
