### ISSUE TITLE
How can I add super channel to AC and N mode

### ISSUE THREAD

**Issue by baalwy** [TobleMiner/nanostation-ac-openwrt-bin#2]
Can you tell me how I add all super channel

**Comment by TobleMiner** [comment]
@baalwy What exactly do you mean by "super channel"? Are you talking about extending the frequency range of your device?
Doing so is easy on AirOS but a lot harder on OpenWrt. Extending support to all channels supported woldwide is relatively easy. There is a file called `db.txt` in the openwrt tree once the firmware has been compiled. It contains the regulatory restrictions applied to wireless devices. You can simply modify it and compile the firmware again. This will result in firnware where the kernel will not limit channel use anymore. I have to stress that you may of course only do this in compliance with your local regulations.

There might be additional pitfalls though. Especially if you are planning on operating outside of the assigned wifi channels you will need to modify the channel list known to cfg80211.
Additionally the atheros chipset might require special configuration not supported by Linux. You will have to test that though.

P.S.: Please don't spam your question over all threads including this device. I would suggest opening a thread on the OpenWrt forum for this and being a little more verbose in what exactly you are trying to achieve.

**Comment by baalwy** [comment]
i mean on PowerBeam M5 400 original software I see Country Code: Licensed
and I see all channels available and Output Power 26dbm
on nanostiation AC loco on stock firmware i changes the Country Code: Licensed 
and i see  all channels available and Output Power 25dbm 
but on openwrt the Output Power 23 dbm maxim
and there only a few channels 
i hop to help me how do i add all channels and increase Output Power

**Comment by TobleMiner** [comment]
Yes. This is indeed normal. The open-source Linux kernel drivers have no concept of licensed operation. They are in fact confined to "normal" WLAN usage. As I've told you you can somewhat extend that range by modifying the regulatory database. Other than that I've no experience on operation outside of the usual frequency bands. Please open a thread at the openwrt forum. Someone over there might be able to help you.
